### ISSUE TITLE
repository not found when installing

### ISSUE THREAD

**Issue by francbartoli** [boundlessgeo/sdk-apps#10]
This error below is raised when I run `npm i` following [How to use](https://github.com/boundlessgeo/sdk-apps/blob/master/README.md) section
> npm ERR! fatal: repository 'https://github.com/boundlessgeo/sdk-tools.git/' not found

**Comment by bartvde** [comment]
ah look like that one is still private, @tingold any chance you can open up sdk-tools as well?

**Comment by bartvde** [comment]
@francbartoli can you retry? Should be public now.

**Comment by francbartoli** [comment]
@bartvde now it works well, I have build and run successfully wfst thanks. @tingold not sure if makes sense but I would suggest to publish [sdk](https://github.com/boundlessgeo/sdk), [sdk-apps](https://github.com/boundlessgeo/sdk-apps), [sdk-tools](https://github.com/boundlessgeo/sdk-tools) on public npm repos also, before someone else fork github repos and does it
